smash/smash/urls.py
import re

from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import re_path
from django.views.static import serve
from two_factor.urls import urlpatterns as tf_urls

from web import api_urls
from web import urls

handler404 = "web.views.e404_page_not_found"
handler500 = "web.views.e500_error"
handler403 = "web.views.e403_permission_denied"
handler400 = "web.views.e400_bad_request"

if settings.SMASCH_PATH_PREFIX != "":
    url_prefix = settings.SMASCH_PATH_PREFIX.lstrip("/").rstrip("/") + "/"
else:
    url_prefix = ""

urlpatterns = [
    re_path(rf"^{url_prefix}admin/", admin.site.urls),
    re_path(rf"{url_prefix}", include(urls)),
    re_path(rf"^{url_prefix}api/", include(api_urls)),
    re_path(rf"{url_prefix}", include(tf_urls)),
]

if settings.SERVE_STATIC or settings.DEBUG:
    urlpatterns.append(
        re_path(
            r"^%s(?P<path>.*)$" % re.escape(settings.MEDIA_URL.lstrip("/")),
            serve,
            {"document_root": settings.MEDIA_ROOT},
        )
    )

smash/web/urls.py
from django.conf import settings
from django.conf.urls import include
from django.urls import re_path
from django.contrib.auth.views import LogoutView
from django.views.defaults import page_not_found

from web import views
from web.views import subject_types
from web.views.daily_planning import TemplateDailyPlannerView

urlpatterns = [
    # make sure that users cannot disable two factors authentication
    re_path(r"^account/two_factor/disable/$", page_not_found, {"exception": Exception("Not Found")}),
    re_path(r"^change_password/$", views.password.change_password, name="change_password"),
    re_path(
        r"^appointment_types/$",
        views.appointment_type.AppointmentTypeListView.as_view(),
        name="web.views.appointment_types",
    ),
    re_path(
        r"^appointment_types/add$",
        views.appointment_type.AppointmentTypeCreateView.as_view(),
        name="web.views.appointment_type_add",
    ),
    re_path(
        r"^appointment_types/(?P<pk>\d+)/edit$",
        views.appointment_type.AppointmentTypeEditView.as_view(),
        name="web.views.appointment_type_edit",
    ),
    re_path(
        r"^appointment_types/(?P<pk>\d+)/delete$",
        views.appointment_type.AppointmentTypeDeleteView.as_view(),
        name="web.views.appointment_type_delete",
    ),
    ####################
    #   APPOINTMENTS   #
    ####################
    re_path(r"^appointments$", views.appointment.appointments, name="web.views.appointments"),
    re_path(
        r"^appointments/unfinished$",
        views.appointment.unfinished_appointments,
        name="web.views.unfinished_appointments",
    ),
    re_path(
        r"^appointments/add/(?P<visit_id>\d+)$", views.appointment.appointment_add, name="web.views.appointment_add"
    ),
    re_path(r"^appointments/add/general$", views.appointment.appointment_add, name="web.views.appointment_add_general"),
    re_path(
        r"^appointments/edit/(?P<appointment_id>\d+)$",
        views.appointment.appointment_edit,
        name="web.views.appointment_edit",
    ),
    re_path(
        r"^appointments/delete/(?P<pk>\d+)$",
        views.appointment.AppointmentDeleteView.as_view(),
        name="web.views.appointment_delete",
    ),
    ####################
    #      VISITS      #
    ####################
    re_path(r"^visits$", views.visit.visits, name="web.views.visits"),
    re_path(r"^visits/exceeded$", views.visit.exceeded_visits, name="web.views.exceeded_visits"),
    re_path(r"^visits/unfinished$", views.visit.unfinished_visits, name="web.views.unfinished_visits"),
    re_path(
        r"^visits/approaching$",
        views.visit.approaching_visits_without_appointments,
        name="web.views.approaching_visits_without_appointments",
    ),
    re_path(
        r"^visits/approaching_post_mail$",
        views.visit.approaching_visits_for_mail_contact,
        name="web.views.approaching_visits_for_mail_contact",
    ),
    re_path(
        r"^visits/missing_appointments$",
        views.visit.visits_with_missing_appointments,
        name="web.views.visits_with_missing_appointments",
    ),
    re_path(r"^visits/details/(?P<visit_id>\d+)$", views.visit.visit_details, name="web.views.visit_details"),
    re_path(r"^visits/unfinish/(?P<visit_id>\d+)$", views.visit.visit_unfinish, name="web.views.visit_unfinish"),
    re_path(r"^visits/add$", views.visit.visit_add, name="web.views.visit_add"),
    re_path(r"^visits/add/(?P<subject_id>\d+)$", views.visit.visit_add, name="web.views.visit_add"),
    re_path(r"^visit/mark/(?P<visit_id>\d+)/(?P<as_what>[A-z]+)$", views.visit.visit_mark, name="web.views.visit_mark"),
    ####################
    #    SUBJECTS      #
    ####################
    re_path(r"^subjects$", views.subject.subjects, name="web.views.subjects"),
    re_path(r"^subjects/no_visit$", views.subject.subject_no_visits, name="web.views.subject_no_visits"),
    re_path(
        r"^subjects/require_contact$", views.subject.subject_require_contact, name="web.views.subject_require_contact"
    ),
    re_path(r"^subjects/voucher_expiry", views.subject.subject_voucher_expiry, name="web.views.subject_voucher_expiry"),
    re_path(r"^study/(?P<study_id>\d+)/subjects/add$", views.subject.subject_add, name="web.views.subject_add"),
    re_path(
        r"^subjects/subject_visit_details/(?P<subject_id>\d+)$",
        views.subject.subject_visit_details,
        name="web.views.subject_visit_details",
    ),
    re_path(r"^subjects/edit/(?P<subject_id>\d+)$", views.subject.subject_edit, name="web.views.subject_edit"),
    re_path(
        r"^subjects/(?P<pk>\d+)/delete$", views.subject.SubjectDeleteView.as_view(), name="web.views.subject_delete"
    ),
    re_path(
        r"^studysubjects/(?P<pk>\d+)/delete$",
        views.subject.StudySubjectDeleteView.as_view(),
        name="web.views.study_subject_delete",
    ),
    #########################
    # RED CAP NOTIFICATIONS #
    #########################
    re_path(r"^redcap/missing_subjects$", views.redcap.missing_subjects, name="web.views.missing_redcap_subject"),
    re_path(
        r"^redcap/inconsistent_subjects$",
        views.redcap.inconsistent_subjects,
        name="web.views.inconsistent_redcap_subject",
    ),
    ####################
    #    CONTACTS      #
    ####################
    re_path(
        r"^subjects/(?P<subject_id>\d+)/contacts/add$", views.contact_attempt.contact_add, name="web.views.contact_add"
    ),
    re_path(
        r"^subjects/(?P<subject_id>\d+)/contacts/(?P<contact_attempt_id>\d+)/edit",
        views.contact_attempt.contact_edit,
        name="web.views.contact_edit",
    ),
    ####################
    #     DOCTORS      #
    ####################
    re_path(r"^doctors/$", views.worker.worker_list, name="web.views.workers"),
    re_path(r"^doctors/(?P<worker_type>[A-z]+)$", views.worker.worker_list, name="web.views.workers"),
    re_path(r"^doctors/add/(?P<worker_type>[A-z]+)$", views.worker.worker_add, name="web.views.worker_add"),
    re_path(r"^doctors/edit/(?P<worker_id>\d+)$", views.worker.worker_edit, name="web.views.worker_edit"),
    re_path(r"^doctors/disable/(?P<doctor_id>\d+)$", views.worker.worker_disable, name="web.views.worker_disable"),
    re_path(r"^doctors/enable/(?P<doctor_id>\d+)$", views.worker.worker_enable, name="web.views.worker_enable"),
    re_path(
        r"^doctors/(?P<doctor_id>\d+)/availability/add$",
        views.worker.worker_availability_add,
        name="web.views.worker_availability_add",
    ),
    re_path(
        r"^doctors/availability/(?P<availability_id>\d+)/delete$",
        views.worker.worker_availability_delete,
        name="web.views.worker_availability_delete",
    ),
    re_path(
        r"^doctors/availability/(?P<availability_id>\d+)/edit",
        views.worker.worker_availability_edit,
        name="web.views.worker_availability_edit",
    ),
    re_path(
        r"^doctors/(?P<doctor_id>\d+)/holiday/add$",
        views.worker.worker_holiday_add,
        name="web.views.worker_holiday_add",
    ),
    re_path(
        r"^doctors/holiday/(?P<holiday_id>\d+)/delete$",
        views.worker.worker_holiday_delete,
        name="web.views.worker_holiday_delete",
    ),
    ####################
    #    EQUIPMENT     #
    ####################
    re_path(
        r"^equipment_and_rooms$", views.equipment_and_rooms.equipment_and_rooms, name="web.views.equipment_and_rooms"
    ),
    re_path(r"^equipment_and_rooms/equipment$", views.equipment.equipment, name="web.views.equipment"),
    re_path(r"^equipment_and_rooms/equipment/add$", views.equipment.equipment_add, name="web.views.equipment_add"),
    re_path(
        r"^equipment_and_rooms/equipment/edit/(?P<equipment_id>\d+)$",
        views.equipment.equipment_edit,
        name="web.views.equipment_edit",
    ),
    re_path(
        r"^equipment_and_rooms/equipment/delete/(?P<equipment_id>\d+)$",
        views.equipment.equipment_delete,
        name="web.views.equipment_delete",
    ),
    re_path(r"^equipment_and_rooms/kit_requests$", views.kit.kit_requests, name="web.views.kit_requests"),
    re_path(
        r"^equipment_and_rooms/kit_requests/(?P<start_date>[\w-]+)/$",
        views.kit.kit_requests_send_mail,
        name="web.views.kit_requests_send_mail",
    ),
    re_path(
        r"^equipment_and_rooms/kit_requests/(?P<start_date>[\w-]+)/(?P<end_date>[\w-]+)/$",
        views.kit.kit_requests_send_mail,
        name="web.views.kit_requests_send_mail",
    ),
    re_path(
        r"^equipment_and_rooms/flying_teams$",
        views.flying_teams.flying_teams,
        name="web.views.equipment_and_rooms.flying_teams",
    ),
    re_path(
        r"^equipment_and_rooms/flying_teams/add$",
        views.flying_teams.flying_teams_add,
        name="web.views.equipment_and_rooms.flying_teams_add",
    ),
    re_path(
        r"^equipment_and_rooms/flying_teams/edit/(?P<flying_team_id>\d+)$",
        views.flying_teams.flying_teams_edit,
        name="web.views.equipment_and_rooms.flying_teams_edit",
    ),
    re_path(r"^equipment_and_rooms/rooms$", views.rooms.rooms, name="web.views.equipment_and_rooms.rooms"),
    re_path(
        r"^equipment_and_rooms/rooms/planning$",
        views.rooms.rooms_planning,
        name="web.views.equipment_and_rooms.rooms_planning",
    ),
    re_path(r"^equipment_and_rooms/rooms/add$", views.rooms.rooms_add, name="web.views.equipment_and_rooms.rooms_add"),
    re_path(
        r"^equipment_and_rooms/rooms/edit/(?P<room_id>\d+)$",
        views.rooms.rooms_edit,
        name="web.views.equipment_and_rooms.rooms_edit",
    ),
    re_path(
        r"^equipment_and_rooms/rooms/delete/(?P<room_id>\d+)$",
        views.rooms.rooms_delete,
        name="web.views.equipment_and_rooms.rooms_delete",
    ),
    re_path(
        r"^study/(?P<study_id>\d+)/subject_types/(?P<subject_type_id>\d+)$",
        subject_types.subject_type_edit,
        name="web.views.subject_type_edit",
    ),
    re_path(

smash/web/models/holiday.py
# coding=utf-8
from django.db import models

from .constants import AVAILABILITY_CHOICES, AVAILABILITY_HOLIDAY


class Holiday(models.Model):
    class Meta:
        app_label = 'web'

    person = models.ForeignKey("web.Worker", on_delete=models.CASCADE,
                               verbose_name='Worker'
                               )
    datetime_start = models.DateTimeField(
        verbose_name='On leave since'
    )
    datetime_end = models.DateTimeField(
        verbose_name='On leave until'
    )

    info = models.TextField(max_length=2000,
                            blank=True,
                            verbose_name='Comments'
                            )

    kind = models.CharField(max_length=1,
                            choices=AVAILABILITY_CHOICES,
                            default=AVAILABILITY_HOLIDAY,
                            help_text='Defines the kind of availability. Either Holiday or Extra Availability.')

    def __str__(self):
        return f"{self.person.first_name} {self.person.last_name}"

smash/web/templates/doctors/add.html
{% extends "_base.html" %}
{% load static %}
{% load filters %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'npm/awesomplete/awesomplete.css' %}"/>
    <style type="text/css">
        .hidden_form_field{
            display: none;
        }
    </style>
{% endblock styles %}


{% block ui_active_tab %}
    {% if worker_type == 'STAFF' %}
        'workers'
    {% elif worker_type == 'HEALTH_PARTNER' %}
        'health_partner'
    {% elif worker_type == 'VOUCHER_PARTNER' %}
        'voucher_partner'
    {% endif %}
{% endblock ui_active_tab %}

{% block page_header %}

    {% if worker_type == 'STAFF' %}
        Add Worker
    {% elif worker_type == 'HEALTH_PARTNER' %}
        Add Health Partner
    {% elif worker_type == 'VOUCHER_PARTNER' %}
        Add Voucher Partner
    {% endif %}

{% endblock page_header %}
{% block page_description %}{% endblock page_description %}

{% block breadcrumb %}
    {% include "doctors/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block maincontent %}

    {% block content %}
        <div class="box box-info">
            <form method="post" action="" class="form-horizontal">
                {% csrf_token %}

                <div class="box-body">
                    <div class="col-sm-6">
                        {% for field in form %}
                            <div class="form-group  {% if field.errors %}has-error{% endif %} {{ field.field.widget.attrs.class }}">
                                <label for="{{ field.id_for_label }}" class="col-sm-4 control-label">
                                    {{ field.label }}
                                    {% if field.help_text %}
                                        <i class="fa fa-info-circle" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="{{field.help_text}}"></i>
                                    {% endif %}
                                </label>

                                <div class="col-sm-8">
                                    {{ field|add_class:'form-control' }}
                                </div>

                                {% if field.errors %}
                                    <span class="help-block">
                                        {{ field.errors }}
                                     </span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div><!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-block btn-success">{% block save-button %}
                            Add{% endblock %}</button>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'web.views.workers' worker_type %}" class="btn btn-block btn-default"> Cancel</a>
                    </div>
                </div><!-- /.box-footer -->
            </form>
        </div>
    {% endblock %}




{% endblock maincontent %}

{% block scripts %}
    {{ block.super }}

    <script src="{% static 'npm/awesomplete/awesomplete.min.js' %}"></script>
    <script>
        // If ever to debug and thinking why it doesn't work => look if there is 'null' in data from API
        $.get("{% url 'web.api.specializations' %}", function (data) {
            new Awesomplete(document.querySelector("#id_specialization")).list = data.specializations;
        });
        $.get("{% url 'web.api.units' %}", function (data) {
            new Awesomplete(document.querySelector("#id_unit")).list = data.units;
        });
    </script>

{% endblock scripts %}

smash/web/templates/doctors/add_availability.html
{% extends "_base.html" %}
{% load static %}
{% load filters %}

{% block styles %}
    {{ block.super }}
    {% include "includes/datetimepicker.css.html" %}
{% endblock styles %}

{% block ui_active_tab %}'workers'{% endblock ui_active_tab %}
{% block page_header %}Create new availability for <span class="doctor_name">{{ doctor_name }}</span>{% endblock page_header %}
{% block page_description %}{% endblock page_description %}

{% block title %}{{ block.super }} - Add availability{% endblock %}

{% block breadcrumb %}
    {% include "doctors/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block maincontent %}

    {% block content %}
        <div class="box box-info">
            <div class="box-header with-border">
                <a href="{% url 'web.views.worker_edit' doctor_id %}" class="btn btn-block btn-default">Go back (without
                    changes)</a>
            </div>

            <form method="post" action="" class="form-horizontal">
                {% csrf_token %}

                <div class="box-body">
                    <div class="col-sm-6">
                        {% for field in form %}
                            <div class="form-group  {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_label }}" class="col-sm-4 control-label">
                                    {{ field.label }}
                                </label>

                                <div class="col-sm-8">
                                    {{ field|add_class:'form-control' }}
                                </div>

                                {% if field.errors %}
                                    <span class="help-block">
                                        {{ field.errors }}
                                     </span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div><!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-block btn-success">Add</button>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'web.views.worker_edit' doctor_id %}"
                           class="btn btn-block btn-default">Cancel</a>
                    </div>
                </div><!-- /.box-footer -->
            </form>
        </div>
    {% endblock %}

{% endblock maincontent %}

{% block scripts %}
    {{ block.super }}

    {% include "includes/datetimepicker.js.html" %}
{% endblock scripts %}

smash/web/templates/doctors/add_holiday.html
{% extends "_base.html" %}
{% load static %}
{% load filters %}

{% block styles %}
    {{ block.super }}
    {% include "includes/datetimepicker.css.html" %}
    <link rel="stylesheet" href="{% static 'npm/awesomplete/awesomplete.css' %}"/>
    <style type="text/css">
        .doctor_name {
            border-bottom: black 1px solid;
        }
    </style>
{% endblock styles %}

{% block ui_active_tab %}'workers'{% endblock ui_active_tab %}
{% block page_header %}Create new holiday or extra availability for <span class="doctor_name">{{ doctor_name }}</span>{% endblock page_header %}
{% block page_description %}{% endblock page_description %}

{% block title %}{{ block.super }} - Add availability{% endblock %}

{% block breadcrumb %}
    {% include "doctors/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block maincontent %}

    {% block content %}
        <div class="box box-info">
            <div class="box-header with-border">
                <a href="{% url 'web.views.worker_edit' doctor_id %}" class="btn btn-block btn-default">Go back (without
                    changes)</a>
            </div>

            <form id="add_holiday_form" method="post" action="" class="form-horizontal">
                {% csrf_token %}

                <div class="box-body">
                    <div class="col-sm-6">
                        {% for field in form %}
                            <div class="form-group  {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_label }}" class="col-sm-4 control-label">
                                    {{ field.label }}
                                    {% if field.help_text %}
                                        <i class="fa fa-info-circle" aria-hidden="true" data-toggle="tooltip" data-placement="top" title="{{field.help_text}}"></i>
                                    {% endif %}
                                </label>
                                <div class="col-sm-8">
                                    {{ field|add_class:'form-control' }}
                                </div>

                                {% if field.errors %}
                                    <span class="help-block">
                                        {{ field.errors }}
                                     </span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div><!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-block btn-success">Add</button>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'web.views.worker_edit' doctor_id %}"
                           class="btn btn-block btn-default">Cancel</a>
                    </div>
                </div><!-- /.box-footer -->
            </form>
        </div>
    {% endblock %}

{% endblock maincontent %}

{% block scripts %}
    {{ block.super }}

    {% include "includes/datetimepicker.js.html" %}
    <script>
        $(function(){
            $('#add_holiday_form').on('submit', function(e){
                var start = moment($('#id_datetime_start').val());
                var end = moment($('#id_datetime_end').val());
                if(end <= start){
                    e.preventDefault();
                    alert('End date must be greater than start date.');
                    return false;
                }
                return true;
            });
        })
    </script>
{% endblock scripts %}

smash/web/templates/doctors/breadcrumb.html
<li><a href="{% url 'web.views.appointments' %}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
{% if worker_type == 'HEALTH_PARTNER' %}
    <li>Configuration</li>
    <li class="active"><a href="{% url 'web.views.workers' worker_type %}">Health Partners</a></li>
{% elif worker_type == 'VOUCHER_PARTNER' %}
    <li>Voucher</li>
    <li class="active"><a href="{% url 'web.views.workers' worker_type %}">Voucher Partners</a></li>
{% else %}
    <li class="active"><a href="{% url 'web.views.workers' 'STAFF' %}">Workers</a></li>
{% endif %}

smash/web/templates/doctors/change_password.html
{% extends "_base.html" %}
{% load static %}
{% load filters %}

{% block styles %}
    {{ block.super }}
    <!-- DataTables -->
    <link rel="stylesheet" href="{% static 'npm/datatables.net-bs/css/dataTables.bootstrap.css' %}">
    <style type="text/css">
        .hidden_form_field{
            display: none;
        }
        form.password_change{
        	display: grid;
    		max-width: 400px;
        }
        button[type=submit]{
        	margin-top: 15px;
        }
    </style>
{% endblock styles %}

{% block ui_active_tab %}'workers'{% endblock ui_active_tab %}

{% block title %}{{ block.super }} - Change password {% endblock %}

{% block page_header %} Changing password for worker <b>{{ worker }}</b> with username: <b>{{ user }}</b> {% endblock page_header %}

{% block breadcrumb %}
    {% include "doctors/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block maincontent %}

    {% block content %}

<form class="password_change" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Save changes</button>
</form>


{% endblock %}

{% endblock maincontent %}

{% block scripts %}
    {{ block.super }}

{% endblock scripts %}

smash/web/templates/doctors/edit_availability.html
{% extends "_base.html" %}
{% load static %}
{% load filters %}

{% block styles %}
    {{ block.super }}
    <!-- DataTables -->
    {% include "includes/datetimepicker.css.html" %}
{% endblock styles %}

{% block ui_active_tab %}'workers'{% endblock ui_active_tab %}
{% block page_header %}Edit availability{% endblock page_header %}
{% block page_description %}{% endblock page_description %}

{% block title %} - Edit worker availability{% endblock %}

{% block breadcrumb %}
    {% include "doctors/breadcrumb.html" %}
{% endblock breadcrumb %}

{% block maincontent %}

    {% block content %}
        <div class="box box-info">
            <div class="box-header with-border">
                <a href="{% url 'web.views.worker_edit' doctor_id %}" class="btn btn-block btn-default">Go back (without
                    changes)</a>
            </div>

            <form method="post" action="" class="form-horizontal">
                {% csrf_token %}

                <div class="box-body">
                    <div class="col-sm-6">
                        {% for field in form %}
                            <div class="form-group  {% if field.errors %}has-error{% endif %}">
                                <label for="{{ field.id_for_label }}" class="col-sm-4 control-label">
                                    {{ field.label }}
                                </label>

                                <div class="col-sm-8">
                                    {{ field|add_class:'form-control' }}
                                </div>

                                {% if field.errors %}
                                    <span class="help-block">
                                        {{ field.errors }}
                                     </span>
                                {% endif %}
                            </div>
                        {% endfor %}
                    </div>
                </div><!-- /.box-body -->

                <div class="box-footer">
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-block btn-success">Save</button>
                    </div>
                    <div class="col-sm-6">
                        <a href="{% url 'web.views.worker_edit' doctor_id %}"
                           class="btn btn-block btn-default">Cancel</a>
                    </div>
                </div><!-- /.box-footer -->
            </form>
        </div>
    {% endblock %}



{% endblock maincontent %}

{% block scripts %}
    {{ block.super }}
    {% include "includes/datetimepicker.js.html" %}
{% endblock scripts %}